# Schema for the configuration files of the less module.

less.settings:
  type: config_object
  label: 'LESS settings'
  mapping:
    engine:
      type: string
      label: 'Engine'
    developer_options:
      type: mapping
      label: 'Developer Options'
      mapping:
        devel:
          type: boolean
          label: 'LESS developer mode'
        source_maps:
          type: boolean
          label: 'Source Maps'
        watch_mode:
          type: boolean
          label: 'Watch Mode'
